### ISSUE TITLE
\WebviewTestAot\bin\Debug\net9.0-windows\Data\image\remove.png NotFound

### ISSUE THREAD

**Issue by typetrade** [shshshdy/Webview2Aot#1]
System.IO.DirectoryNotFoundException:“Could not find a part of the path 'C:\Users\steve.TAO\Downloads\Webview2Aot-main\Webview2Aot-main\WebviewTestAot\bin\Debug\net9.0-windows\Data\image\remove.png'.”

var path = Path.Combine(AppContext.BaseDirectory, "Data", "image", "remove.png");
var bytes = File.ReadAllBytes(path);

源代码没有这个图片

**Comment by shshshdy** [comment]
添加了，需要自己放到对应目录
